name: pennypal
description: A gamified personal finance app that makes budgeting fun
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Architecture
  go_router: ^14.0.0
  flutter_riverpod: ^2.5.0
  
  # Data & Networking
  dio: ^5.5.0
  http: ^1.0.0
  appwrite: ^11.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # UI & UX
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.68.0
  lottie: ^3.1.0
  google_fonts: ^6.2.1
  confetti: ^0.7.0
  flutter_animate: ^4.5.0
  
  # Utilities
  intl: ^0.19.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  
  # Monitoring
  sentry_flutter: ^8.9.0

  # Icons & UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/images/background_news.png
    - assets/icons/
    - assets/animations/
    - assets/data/

  # Fonts will be configured later with Google Fonts